export const handyImages = [
  { id: 1, url: "./handicrafts/IMG_1357.jpg", alt: "Handicraft 1" },
  { id: 2, url: "./handicrafts/IMG_1358.jpg", alt: "Handicraft 2" },
  { id: 3, url: "./handicrafts/IMG_1359.jpg", alt: "Handicraft 3" },
  { id: 4, url: "./handicrafts/IMG_1361.jpg", alt: "Handicraft 4" },
  { id: 5, url: "./handicrafts/IMG_1362.jpg", alt: "Handicraft 5" },
  { id: 6, url: "./handicrafts/IMG_1363.jpg", alt: "Handicraft 6" },
  { id: 7, url: "./handicrafts/IMG_1364.jpg", alt: "Handicraft 7" },
  { id: 8, url: "./handicrafts/IMG_1365.jpg", alt: "Handicraft 8" },
  { id: 9, url: "./handicrafts/IMG_1400.jpg", alt: "Handicraft 9" },
  { id: 10, url: "./handicrafts/IMG_1404.jpg", alt: "Handicraft 10" },
  { id: 11, url: "./handicrafts/IMG_1406.jpg", alt: "Handicraft 11" },
  { id: 12, url: "./handicrafts/IMG_1407.jpg", alt: "Handicraft 12" },
  { id: 13, url: "./handicrafts/IMG_1410.jpg", alt: "Handicraft 13" },
  { id: 14, url: "./handicrafts/IMG_1412.jpg", alt: "Handicraft 14" },
  { id: 15, url: "./handicrafts/IMG_1413.jpg", alt: "Handicraft 15" },
  { id: 16, url: "./handicrafts/IMG_1415.jpg", alt: "Handicraft 16" },
  { id: 17, url: "./handicrafts/IMG_1417.jpg", alt: "Handicraft 17" },
  { id: 18, url: "./handicrafts/IMG_1418.jpg", alt: "Handicraft 18" },
  { id: 19, url: "./handicrafts/IMG_1420.jpg", alt: "Handicraft 19" },
  { id: 20, url: "./handicrafts/IMG_1421.jpg", alt: "Handicraft 20" },
  { id: 21, url: "./handicrafts/IMG_1422.jpg", alt: "Handicraft 21" },
  { id: 22, url: "./handicrafts/IMG_1423.jpg", alt: "Handicraft 22" },
];
export const paintingImages = [
  { id: 1, url: "./painting/IMG_1319.jpg", alt: "painting" },
  { id: 2, url: "./painting/IMG_1324.jpg", alt: "painting" },
  { id: 3, url: "./painting/IMG_1325.jpg", alt: "painting" },
  { id: 4, url: "./painting/IMG_1326.jpg", alt: "painting" },
  { id: 5, url: "./painting/IMG_1327.jpg", alt: "painting" },
  { id: 6, url: "./painting/IMG_1336.jpg", alt: "painting" },
  { id: 7, url: "./painting/IMG_1337.jpg", alt: "painting" },
  { id: 8, url: "./painting/IMG_1338.jpg", alt: "painting" },
  { id: 9, url: "./painting/IMG_1340.jpg", alt: "painting" },
  { id: 10, url: "./painting/IMG_1341.jpg", alt: "painting" },
  { id: 11, url: "./painting/IMG_1342.jpg", alt: "painting" },
  { id: 12, url: "./painting/IMG_1343.jpg", alt: "painting" },
  { id: 13, url: "./painting/IMG_1344.jpg", alt: "painting" },
  { id: 14, url: "./painting/IMG_1345.jpg", alt: "painting" },
  { id: 15, url: "./painting/IMG_1346.jpg", alt: "painting" },
  { id: 16, url: "./painting/IMG_1347.jpg", alt: "painting" },
  { id: 17, url: "./painting/IMG_1348.jpg", alt: "painting" },
  { id: 18, url: "./painting/IMG_1349.jpg", alt: "painting" },
  { id: 19, url: "./painting/IMG_1350.jpg", alt: "painting" },
  { id: 20, url: "./painting/IMG_1351.jpg", alt: "painting" },
  { id: 21, url: "./painting/IMG_1352.jpg", alt: "painting" },
  { id: 22, url: "./painting/IMG_1353.jpg", alt: "painting" },
  { id: 23, url: "./painting/IMG_1354.jpg", alt: "painting" },
  { id: 24, url: "./painting/IMG_1355.jpg", alt: "painting" },
  { id: 25, url: "./painting/IMG_1356.jpg", alt: "painting" },
  { id: 26, url: "./painting/IMG_1367.jpg", alt: "painting" },
  { id: 27, url: "./painting/IMG_1368.jpg", alt: "painting" },
  { id: 28, url: "./painting/IMG_1370.jpg", alt: "painting" },
  { id: 29, url: "./painting/IMG_1371.jpg", alt: "painting" },
  { id: 30, url: "./painting/IMG_1372.jpg", alt: "painting" },
  { id: 31, url: "./painting/IMG_1374.jpg", alt: "painting" },
  { id: 32, url: "./painting/IMG_1375.jpg", alt: "painting" },
  { id: 33, url: "./painting/IMG_1376.jpg", alt: "painting" },
  { id: 34, url: "./painting/IMG_1377.jpg", alt: "painting" },
  { id: 35, url: "./painting/IMG_1378.jpg", alt: "painting" },
  { id: 36, url: "./painting/IMG_1379.jpg", alt: "painting" },
  { id: 37, url: "./painting/IMG_1380.jpg", alt: "painting" },
  { id: 38, url: "./painting/IMG_1381.jpg", alt: "painting" },
  { id: 39, url: "./painting/IMG_1382.jpg", alt: "painting" },
  { id: 40, url: "./painting/IMG_1383.jpg", alt: "painting" },
  { id: 41, url: "./painting/IMG_1384.jpg", alt: "painting" },
  { id: 42, url: "./painting/IMG_1385.jpg", alt: "painting" },
  { id: 43, url: "./painting/IMG_1386.jpg", alt: "painting" },
  { id: 44, url: "./painting/IMG_1387.jpg", alt: "painting" },
  { id: 45, url: "./painting/IMG_1388.jpg", alt: "painting" },
  { id: 46, url: "./painting/IMG_1389.jpg", alt: "painting" },
  { id: 47, url: "./painting/IMG_1390.jpg", alt: "painting" },
  { id: 48, url: "./painting/IMG_1391.jpg", alt: "painting" },
  { id: 49, url: "./painting/IMG_1393.jpg", alt: "painting" },
  { id: 50, url: "./painting/IMG_1395.jpg", alt: "painting" },
  { id: 51, url: "./painting/IMG_1397.jpg", alt: "painting" },
];
export const graphicImages = [
  { id: 1, url: "./graphic-logo/IMG_1017.png", alt: "graphic" },
  { id: 2, url: "./graphic-logo/IMG_1020.png", alt: "graphic" },
  { id: 3, url: "./graphic-logo/Artwork1.png", alt: "graphic" },
  { id: 4, url: "./graphic-logo/Artwork2.png", alt: "graphic" },
  { id: 5, url: "./graphic-logo/Artwork3.png", alt: "graphic" },
  { id: 6, url: "./graphic-logo/Artwork4.png", alt: "graphic" },
  { id: 7, url: "./graphic-logo/IMG_1090.jpg", alt: "graphic" },
  { id: 8, url: "./graphic-logo/IMG_1117.jpg", alt: "graphic" },
  { id: 9, url: "./graphic-logo/IMG_1196.jpg", alt: "graphic" },
  { id: 10, url: "./graphic-logo/IMG_1006.jpg", alt: "graphic" },
];
export const designImages = [
  { id: 1, url: "./design/IMG_0846.PNG", alt: "design" },
  { id: 2, url: "./design/IMG_0858.jpg", alt: "design" },
  { id: 3, url: "./design/IMG_0864.jpg", alt: "design" },
  { id: 4, url: "./design/IMG_0870.jpg", alt: "design" },
  { id: 5, url: "./design/IMG_0874.PNG", alt: "design" },
  { id: 6, url: "./design/IMG_0940.jpg", alt: "design" },
  { id: 7, url: "./design/IMG_0952.PNG", alt: "design" },
  { id: 8, url: "./design/IMG_0953.PNG", alt: "design" },
  { id: 9, url: "./design/IMG_1078.jpg", alt: "design" },
  { id: 10, url: "./design/IMG_1080.jpg", alt: "design" },
  { id: 11, url: "./design/IMG_1081.jpg", alt: "design" },
  { id: 12, url: "./design/IMG_1082.jpg", alt: "design" },
  { id: 13, url: "./design/IMG_1105.jpg", alt: "design" },
  { id: 14, url: "./design/IMG_1112.jpg", alt: "design" },
  { id: 15, url: "./design/IMG_1278.jpg", alt: "design" },
  { id: 16, url: "./design/IMG_1447.PNG", alt: "design" },
  { id: 17, url: "./design/IMG_1449.jpg", alt: "design" },
  { id: 18, url: "./design/IMG_1460.PNG", alt: "design" },
  { id: 19, url: "./design/IMG_1461.PNG", alt: "design" },
  { id: 20, url: "./design/IMG_1463.PNG", alt: "design" },
  { id: 21, url: "./design/IMG_1283.png", alt: "design" },
  { id: 22, url: "./design/IMG_1289.png", alt: "design" },
  { id: 23, url: "./design/IMG_1291.png", alt: "design" },
  { id: 24, url: "./design/IMG_1295.png", alt: "design" },
  { id: 25, url: "./design/IMG_1297.png", alt: "design" },
  { id: 26, url: "./design/IMG_1303.png", alt: "design" },
  { id: 27, url: "./design/IMG_1306.png", alt: "design" },
  { id: 28, url: "./design/IMG_1307.png", alt: "design" },
  { id: 29, url: "./design/IMG_1308.png", alt: "design" },
  { id: 30, url: "./design/IMG_1309.png", alt: "design" },
  { id: 31, url: "./design/IMG_1310.png", alt: "design" },
  { id: 32, url: "./design/IMG_1316.png", alt: "design" },
  { id: 32, url: "./design/IMG_1316.png", alt: "design" },
];

export const illustrationImages = [
  { id: 1, url: "./illustration/artwork6.png", alt: "illustration" },
  { id: 2, url: "./illustration/IMG_0993.jpg", alt: "illustration" },
  { id: 3, url: "./illustration/artwork1.png", alt: "illustration" },
  { id: 4, url: "./illustration/artwork2.png", alt: "illustration" },
  { id: 21, url: "./illustration/IMG_0994.jpg", alt: "illustration" },
  { id: 19, url: "./illustration/IMG_1092.jpg", alt: "illustration" },
  { id: 20, url: "./illustration/IMG_1093.jpg", alt: "illustration" },
  { id: 21, url: "./illustration/IMG_1094.jpg", alt: "illustration" },
  { id: 6, url: "./illustration/IMG_1030.jpg", alt: "illustration" },
  { id: 7, url: "./illustration/IMG_1031.jpg", alt: "illustration" },
  { id: 8, url: "./illustration/IMG_1032.jpg", alt: "illustration" },
  { id: 9, url: "./illustration/IMG_1034.jpg", alt: "illustration" },
  { id: 10, url: "./illustration/IMG_1035.jpg", alt: "illustration" },
  { id: 11, url: "./illustration/IMG_1036.jpg", alt: "illustration" },
  { id: 12, url: "./illustration/IMG_1049.jpg", alt: "illustration" },
  { id: 13, url: "./illustration/IMG_1057.jpg", alt: "illustration" },
  { id: 14, url: "./illustration/IMG_1059.png", alt: "illustration" },
  { id: 15, url: "./illustration/IMG_1132.png", alt: "illustration" },
  { id: 16, url: "./illustration/artwork3.png", alt: "illustration" },
  { id: 17, url: "./illustration/artwork4.png", alt: "illustration" },
  { id: 18, url: "./illustration/artwork5.png", alt: "illustration" },
];

export const HeroInfo = {
  content: "One of the women artists around the world in 2019",
  imageHero: "./Hero.jpg",
  imageBook: "./book.jpg",
};
